// Generated by dojo-bindgen on Mon, 13 Oct 2025 15:57:53 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `dojo_starter::models::Vec2i` struct


// Model definition for `dojo_starter::models::SpellInstance` model
public class dojo_starter_SpellInstance : ModelInstance {
    [ModelField("instance_id")]
        public FieldElement instance_id;

        [ModelField("spell_id")]
        public FieldElement spell_id;

        [ModelField("caster")]
        public FieldElement caster;

        [ModelField("origin")]
        public Vec2i origin;

        [ModelField("direction")]
        public short direction;

        [ModelField("timestamp")]
        public ulong timestamp;

        [ModelField("damage")]
        public ushort damage;

        [ModelField("speed")]
        public ushort speed;

        [ModelField("lifetime")]
        public ushort lifetime;

        [ModelField("is_active")]
        public bool is_active;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        