// Generated by dojo-bindgen on Sat, 11 Oct 2025 20:00:04 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `dojo_starter::models::GameSession` model
public class dojo_starter_GameSession : ModelInstance {
    [ModelField("session_id")]
        public FieldElement session_id;

        [ModelField("player_1")]
        public FieldElement player_1;

        [ModelField("player_2")]
        public FieldElement player_2;

        [ModelField("started_at")]
        public ulong started_at;

        [ModelField("is_active")]
        public bool is_active;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        