// Generated by dojo-bindgen on Tue, 14 Oct 2025 16:00:08 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `dojo_starter::models::EnemyType` enum
public abstract record EnemyType() : Enum {
    public record Witch() : EnemyType;
    public record Boss() : EnemyType;
}


// Model definition for `dojo_starter::models::Enemy` model
public class dojo_starter_Enemy : ModelInstance {
    [ModelField("enemy_id")]
        public FieldElement enemy_id;

        [ModelField("enemy_type")]
        public EnemyType enemy_type;

        [ModelField("posx")]
        public int posx;

        [ModelField("posy")]
        public int posy;

        [ModelField("velocity")]
        public short velocity;

        [ModelField("health")]
        public ushort health;

        [ModelField("max_health")]
        public ushort max_health;

        [ModelField("damage_per_attack")]
        public ushort damage_per_attack;

        [ModelField("is_alive")]
        public bool is_alive;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        