// Generated by dojo-bindgen on Mon, 13 Oct 2025 15:57:53 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `dojo_starter::models::PlayerSpellbook` model
public class dojo_starter_PlayerSpellbook : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("equipped_spells")]
        public FieldElement[] equipped_spells;

        [ModelField("active_spell_index")]
        public byte active_spell_index;

        [ModelField("cooldowns")]
        public ulong[] cooldowns;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        