// Generated by dojo-bindgen on Sat, 11 Oct 2025 20:00:04 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `dojo_starter::models::PlayerStats` model
public class dojo_starter_PlayerStats : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("health")]
        public ushort health;

        [ModelField("max_health")]
        public ushort max_health;

        [ModelField("mana")]
        public ushort mana;

        [ModelField("max_mana")]
        public ushort max_mana;

        [ModelField("spell_damage_dealt")]
        public uint spell_damage_dealt;

        [ModelField("spells_fired")]
        public uint spells_fired;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        